<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN51006766" failures="9" tests="16" name="Test" time="19.46" errors="0" timestamp="23 Feb 2022 12:33:38 GMT">
  <testcase classname="dataDriveTestingPackage.DataDrivenTest_AddNewEmployees" name="postNewEmployee" time="2.345">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dataDriveTestingPackage.DataDrivenTest_AddNewEmployees.postNewEmployee(DataDrivenTest_AddNewEmployees.java:34)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- postNewEmployee -->
  <testcase classname="testAPI.TC001_GET_Request" name="getweatherDetails" time="1.518">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at testAPI.TC001_GET_Request.getweatherDetails(TC001_GET_Request.java:32)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- getweatherDetails -->
  <testcase classname="testAPI.TC005_GET_Request_Validating_JSONResponse" name="getJSONDetails" time="0.608"/>
  <testcase classname="testAPI.TC002_POST_Request" name="registrationSuccessful" time="1.138"/>
  <testcase classname="testAPI.TC007_GET_Authorization_Request" name="getAuthorizationRequest" time="0.036">
    <failure type="java.net.UnknownHostException" message="No such host is known (restapi.demoqa.com)">
      <![CDATA[java.net.UnknownHostException: No such host is known (restapi.demoqa.com)
at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932)
at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517)
at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851)
at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507)
at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366)
at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300)
at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:263)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:162)
at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:2146)
at io.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:494)
at io.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:451)
at io.restassured.internal.http.HTTPBuilder$request$3.call(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1544)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1293)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:152)
at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
at io.restassured.filter.Filter$filter$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at io.restassured.filter.Filter$filter.call(Unknown Source)
at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
at io.restassured.filter.Filter$filter.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at io.restassured.filter.Filter$filter$0.call(Unknown Source)
at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
at io.restassured.filter.FilterContext$next.call(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1749)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.RequestSpecificationImpl.request(RequestSpecificationImpl.groovy:295)
at io.restassured.internal.RequestSpecificationImpl.request(RequestSpecificationImpl.groovy)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.RequestSpecificationImpl.request(RequestSpecificationImpl.groovy:291)
at io.restassured.internal.RequestSpecificationImpl.request(RequestSpecificationImpl.groovy)
at testAPI.TC007_GET_Authorization_Request.getAuthorizationRequest(TC007_GET_Authorization_Request.java:31)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- getAuthorizationRequest -->
  <testcase classname="testAPI.TC004_GET_Request_PrintAllHeaders" name="getGoogleWeatherAPI" time="0.442"/>
  <testcase classname="dataDriveTestingPackage.dataDrivenTest_003" name="postNewEmployees" time="1.381">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dataDriveTestingPackage.dataDrivenTest_003.postNewEmployees(dataDrivenTest_003.java:38)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- postNewEmployees -->
  <testcase classname="dataDriveTestingPackage.dataDrivenTest_003" name="postNewEmployees" time="1.393">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dataDriveTestingPackage.dataDrivenTest_003.postNewEmployees(dataDrivenTest_003.java:38)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- postNewEmployees -->
  <testcase classname="dataDriveTestingPackage.dataDrivenTest_003" name="postNewEmployees" time="1.443"/>
  <testcase classname="dataDriveTestingPackage.dataDrivenTest_003" name="postNewEmployees" time="1.484"/>
  <testcase classname="dataDriveTestingPackage.dataDrivenTest_003" name="postNewEmployees" time="1.525">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dataDriveTestingPackage.dataDrivenTest_003.postNewEmployees(dataDrivenTest_003.java:38)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- postNewEmployees -->
  <testcase classname="testAPI.TC006_GET_Request_ExtractValuesOfEachNodes" name="getJSONDetails" time="0.628">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at testAPI.TC006_GET_Request_ExtractValuesOfEachNodes.getJSONDetails(TC006_GET_Request_ExtractValuesOfEachNodes.java:26)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
... 32 more
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getJSONDetails -->
  <testcase classname="dataDriveTestingPackage.dataDrivenTest_002" name="postNewEmployees" time="1.441">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dataDriveTestingPackage.dataDrivenTest_002.postNewEmployees(dataDrivenTest_002.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- postNewEmployees -->
  <testcase classname="dataDriveTestingPackage.dataDrivenTest_002" name="postNewEmployees" time="1.372"/>
  <testcase classname="dataDriveTestingPackage.dataDrivenTest_002" name="postNewEmployees" time="1.384">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dataDriveTestingPackage.dataDrivenTest_002.postNewEmployees(dataDrivenTest_002.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- postNewEmployees -->
  <testcase classname="testAPI.TC003_GET_Request" name="googlemapTest" time="0.419"/>
</testsuite> <!-- Test -->
